### ISSUE TITLE
Increase font size for improved readability

### ISSUE THREAD

**Issue by mohomedrishad** [somehq/someblog#3]
The current font size is too small for comfortable reading at 125% screen resolution, commonly used on high-DPI displays. This issue also affects other devices with different resolutions compared to the assumed 100% scaling.

![screenshot](https://github.com/somehq/someblog/assets/151811182/ac0153d1-c455-4ee9-a14c-3a495a6d3172)

**Comment by snelusha** [comment]
Mmm! Sure I will! 😉
